[project]
name = "diffusers-in-comfyui"
description = "A collection of ComfyUI custom nodes that allow to use most Diffusers pipelines and components in Comfy(such as Txt2Img, Img2Img, Inpainting, LoRAS, B-LoRAS, ControlNet...). You will find them under 'Diffusers-in-Comfy'!"
version = "1.0.4"
license = {file = "LICENSE"}
dependencies = ["diffusers @ git+https://github.com/huggingface/diffusers@3bb1fd6fc05917ce2fc577fcda2163391c5bdcc0", "opencv-python==4.10.0.84", "peft==0.14.0", "omegaconf==2.3.0"]

[project.urls]
Repository = "https://github.com/maepopi/Diffusers-in-ComfyUI"
#  Used by Comfy Registry https://comfyregistry.org

[tool.comfy]
PublisherId = "drjusseaux"
DisplayName = "Diffusers-in-ComfyUI"
Icon = ""
